config/routes.rb
Rails.application.routes.draw do
  #root "pages#new"

  #get "about", to: "pages#about"
  #resources :articles

  #get "signup", to: "users#new"
  #resources :users, except: [:new]

  #get "login", to: "sessions#new"
  #post "login", to: "sessions#create"
  #get "logout", to: "sessions#destroy"
  #delete "logout", to: "sessions#destroy"

  root 'pages#home'
  get 'about', to: 'pages#about'
  get 'delete', to: 'articles#delete'
  resources :articles
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  # get 'logout', to: 'sessions#destroy'
  delete 'logout', to: 'sessions#destroy'
  resources :categories, except: [:destroy]
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true, length: { minimum: 6, maximum: 100 }
  validates :description, presence: true, length: { minimum: 10, maximum: 200 }

  belongs_to :user

  has_many :article_categories
  has_many :categories, through: :article_categories

  def self.search(search)
    if search
      article = Article.find_by(title: search)
      if article
        self.where(id: article.id)
      else
        Article.all
      end
    else
      Article.all
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  before_action :set_article, only: [:edit, :update, :show, :destroy]
  before_action :require_user, except: [:index, :show]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def index
    @articles_search = Article.search(params[:search])
    @articles = Article.paginate(page: params[:page], per_page: 4)
  end

  def new
    @article = Article.new
  end


  def create
    @article = Article.new(article_params)
    @article.user = current_user

    respond_to do |format|
      if @article.save
        format.html { redirect_to article_url(@article), notice: "Article was successfully created." }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
    # DRY @artcile = Article.find(params[:id])
  end

  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to article_url(@article), notice: "Article was successfully updated." }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
    # DRY @artcile = Article.find(params[:id])
  end

  def destroy
    @article.destroy

    respond_to do |format|
      format.html { redirect_to articles_url, notice: "Article was successfully destroyed." }
      format.json { head :no_content }
    end
  end


  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :description, category_ids: [])
  end

  def articles_params
    params.require(:article).permit(:search, :title, :description)
  end

  def require_same_user
    if current_user != @article.user
      flash[:alert] = "You can only edit or delete your own article"
      redirect_to articles_path
    end
  end

end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_articles.html.erb
<div class="row">
  <% @articles.each do |article| %>
    <div class="col-sm-6">
      <div class="card text-center shadow p-3 mb-4 bg-body rounded">
        <div class="card-header fst-italic">
          <% if article.user %>
            Featured by: <%= link_to article.user.username, user_path(article.user) %>
          <% end %>
          <div class="mt-2">
          <% if article.categories.any? %>
            <%= render article.categories %>
          <% end %>
          </div>
        </div>
        <div class="card-body">
          <h5 class="card-title"><%= link_to article.title, article_path(article), class: 'text-success' %></h5>
          <p class="card-text"><%= truncate(article.description, length: 40) %></p>
          <%= link_to 'Show', article_path(article), class: 'btn btn-outline-primary' %>
          <% if logged_in? && article.user == current_user %>
            <%= link_to 'Edit', edit_article_path(article), class: 'btn btn-outline-success' %>
            <%= link_to 'Destroy', article_path(article), class: 'btn btn-outline-danger' , data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' } %>
          <% end %>
        </div>
        <div class="card-footer text-muted">
          <small>
            Created <%= time_ago_in_words(article.created_at) %> ago,
            Edited <%= time_ago_in_words(article.updated_at) %> ago
          </small>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/articles/_form.html.erb
<div class="container">
  <%= form_with(model: @article, local: true, data: { turbo: false }) do |f| %>
    <%= render 'shared/errors', obj: @article %>
    <div class="mb-3">
      <%= f.label :title, class: 'form-label' %>
      <%= f.text_field :title, class: 'form-control', placeholder: 'Title of the Article' %>
    </div>
    <div class="mb-3">
      <%= f.label :description, class: 'form-label' %>
      <%= f.text_area :description, class: 'form-control', placeholder: 'Description of the Article', rows: '7', style: 'resize: none' %>
    </div>
    <div class="mb-3">
      <%= f.label :category, class: 'form-label' %>
      <%= f.collection_select( :category_ids, Category.all, :id, :name, { prompt: "Selecciona una o multiples categorias de la lista (O ninguna categoria)" },
          { multiple: true, size: 3, class: 'custom-select form-control' }) %>
    </div>
    <br>
    <div class="btn-group" role="group" aria-label="Form Articles">
      <%= f.submit disable_with: 'Submiting...', class: 'btn btn-success' %>
      <%= link_to 'Back to the List of Articles', articles_path, class: 'btn btn-secondary' %>
    </div>
  <% end  %>
</div>

app/views/articles/edit.html.erb
<h1>Edit Article</h1>
<br>
<%= render "form", article: @article %>

app/views/articles/index.html.erb
<div class="container">
  <div class="generic-container">
    <h1 class="text-center">Listing All Articles</h1>
    <%= render 'layouts/messages' %>
    <% if logged_in? %>
      <%= link_to "Create a new Article", new_article_path, class: 'btn btn-primary mb-2' %>
    <% end %>
    <br>
    <div class="flickr_pagination mb-4">
      <div class="page_info">
        <%= page_entries_info @articles %>
      </div>
      <%= will_paginate @articles, :container => false %>
    </div>
    <%= render "articles" %>
  </div>
</div>

app/views/articles/new.html.erb
<div class="container">
  <div class="generic-container">
    <h1>New Article</h1>
    <br>
    <%= render "form", article: @article %>
  </div>
</div>

app/views/articles/show.html.erb
<div class="container">
  <%= render "layouts/messages" %>
  <div class="generic-container">
    <h1><%= @article.title %></h1>
    <br>
    <div class="card shadow p-3 mb-4 bg-body rounded">
      <div class="card-header fst-italic">
        Featured by: <%= @article.user.username %>
        <%= link_to gravatar_for(@article.user), user_path(@article.user) %>
      </div>
      <div class="card-body">
        <div class="card-text text-start"><%= simple_format(@article.description) %></div>
          <% if @article.categories.any? %>
            <div class="card-header">
                Categories
            </div>
            <div class="mt-2"><%= render @article.categories %></div>
          <% else %>
            No Categories
          <% end %>
        <br/>
        <% if logged_in? and @article.user == current_user %>
          <%= link_to "Edit this Article", edit_article_path, class: "btn btn-outline-primary" %>
          <%= link_to "Delete this Article", article_path(@article), class: "btn btn-outline-danger", data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %>
        <% end %>
        <%= link_to "Back to Articles", articles_path, class: "btn btn-outline-success" %>
      </div>
      <div class="card-footer text-muted">
        <small>
          Created <%= time_ago_in_words(@article.created_at) %> ago,
          Edited <%= time_ago_in_words(@article.updated_at) %> ago
        </small>
      </div>
    </div>
  </div>
</div>