config/routes.rb
Rails.application.routes.draw do
  #root "pages#new"

  #get "about", to: "pages#about"
  #resources :articles

  #get "signup", to: "users#new"
  #resources :users, except: [:new]

  #get "login", to: "sessions#new"
  #post "login", to: "sessions#create"
  #get "logout", to: "sessions#destroy"
  #delete "logout", to: "sessions#destroy"

  root 'pages#home'
  get 'about', to: 'pages#about'
  get 'delete', to: 'articles#delete'
  resources :articles
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  # get 'logout', to: 'sessions#destroy'
  delete 'logout', to: 'sessions#destroy'
  resources :categories, except: [:destroy]
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true, length: { minimum: 3, maximum: 25 }
  validates_uniqueness_of :name
  has_many :article_categories
  has_many :articles, through: :article_categories
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  before_action :set_category, only: [:show, :edit, :update, :destroy]
  before_action :require_user, except: [:index, :show]

  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:notice] = "Category was successfully created"
      redirect_to @category
    else
      render 'new'
    end
  end

  def show
    # @category = Category.find(params[:id])
    @articles = @category.articles.paginate(page: params[:page], per_page: 4)
  end

  def edit 
    # @category = Category.find(params[:id])
  end

  def update
    if @category.update(category_params)
      flash[:notice] = "Category was successfully updated"
      redirect_to category_url
    else
      flash[:alert] = "An erros was found, unprocessable entity"
      render 'edit'
    end
  end

  def destroy
    @category.destroy
    flash[:notice] = "The category was successfully deleted"
    redirect_to categories_url
  end

  private

  def set_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name)
  end
end

app/views/categories/_category.html.erb
<%= link_to category.name, category_path(category), class: "btn rounded-pill bg-info text-dark mr-4" %>

app/views/categories/_form.html.erb
<div class="container">
  <%= form_with(model: @category, local: true, data: { turbo: false }) do |f| %>
    <%= render 'shared/errors', obj: @category %>
    <div class="mb-3">
      <%= f.label :name, "Category Name", class: 'form-label' %>
      <%= f.text_field :name, class: 'form-control', placeholder: 'Enter a new category' %>
    </div>
    <br>
    <div class="btn-group" role="group" aria-label="Form Categories">
      <%= f.submit disable_with: 'Submiting...', class: 'btn btn-success' %>
      <%= link_to 'Return to all categories', categories_path, class: 'btn btn-primary' %>
    </div>
  <% end  %>
</div>

app/views/categories/edit.html.erb
<div class="container">
  <br/>
  <div class="mt-5">
    <h1>Edit Category</h1>
    <%= render 'form', category: @category %>
  </div>
</div>

app/views/categories/index.html.erb
<div class="container">
  <br/>
  <div class="mt-5">
    <h1>List of the all categories</h1>
    <table class="table">
      <thead>
        <tr>
          <th scope="col">Name</th>
          <th scope="col">Total of Articles</th>
          <th scope="col">Actions</th>
        </tr>
      </thead>
      <tbody>
      <% @categories.each do |category| %>
        <tr>
          <th><%= category.name %></th>
          <td><%= pluralize(category.articles.count, "article") %></td>
          <td>
            <%= link_to "Show", category_path(category), class: "btn btn-outline-success" %>
            <% if logged_in? and current_user.admin? %>
              <%= link_to "Edit", edit_category_path(category), class: "btn btn-outline-secondary" %>
            <% end %>
            <%# link_to "Destroy", category_path(category), class: "btn btn-outline-danger disabled", 'data-turbo-method': :delete %>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
  <% if logged_in? and current_user.admin? %>
    <%= link_to "New Category", new_category_path, class: "btn btn-outline-primary" %>
  <% end %>
</div>

app/views/categories/new.html.erb
<div class="container">
  <div class="generic-container">
    <h1>Create a new category</h1>
    <br>
    <%= render "form", category: @category %>
  </div>
</div>

app/views/categories/show.html.erb
<div class="container">
  <br/>
  <div class="mt-5">
    <h1>Show category</h1>
    <h2>The category is: <%= @category.name %></h2>
  </div>
  <div class="text-center mt-4">
      <% if logged_in? and current_user.admin? %>
        <%= link_to "Edit the category", edit_category_path(@category), class: "btn btn-outline-info" %>
      <% end %>
      <%= link_to 'Return to all categories', categories_path, class: 'btn btn-outline-primary' %>
    </div>
    <br>
    <h3 class="text-center">Articles</h3>
    <div class="flickr_pagination mb-3">
      <div class="page_info">
        <%= page_entries_info @articles %>
      </div>
      <%= will_paginate @articles, :container => false %>
    </div>
    <%= render "articles/articles" %>
  </div>
</div>