config/routes.rb
Rails.application.routes.draw do
  #root "pages#new"

  #get "about", to: "pages#about"
  #resources :articles

  #get "signup", to: "users#new"
  #resources :users, except: [:new]

  #get "login", to: "sessions#new"
  #post "login", to: "sessions#create"
  #get "logout", to: "sessions#destroy"
  #delete "logout", to: "sessions#destroy"

  root 'pages#home'
  get 'about', to: 'pages#about'
  get 'delete', to: 'articles#delete'
  resources :articles
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  # get 'logout', to: 'sessions#destroy'
  delete 'logout', to: 'sessions#destroy'
  resources :categories, except: [:destroy]
end

app/views/layouts/_footer.html.erb
<footer class="footer mt-auto py-3 bg-dark text-white fixed-bottom">
  <div class="container text-center">
    <span class="text-muted">Alpha Blog &copy2022</span>
  </div>
</footer>

app/views/layouts/_messages.html.erb
<% if notice %>
  <div class="alert alert-success alert-dismissible fade show success" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
  <div class="container-fluid">
    <%= link_to "Alpha Blogs", root_path, class: "logo navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= create_active_link "Bloggers", users_path, ["nav-link"] %>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle <%= define_active_link "articles" %>"
            href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Articles
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><%= create_active_link "List All Articles", articles_path, ["dropdown-item"] %></li>
            <% if logged_in? %>
            <li><%= create_active_link "New Article", new_article_path, ["dropdown-item"] %></li>
            <% end %>
          </ul>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle <%= define_active_link "categories" %>"
            href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Categories
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><%= create_active_link "List All Categories", categories_path, ["dropdown-item"] %></li>
            <% if logged_in? %>
            <li><%= create_active_link "New Category", new_category_path, ["dropdown-item"] %></li>
            <% end %>
          </ul>
        </li>
        <li class="nav-item">
          <%= create_active_link "About Alpha Blog", about_path, ["nav-link"] %>
        </li>
        <% if logged_in? %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle <%= define_active_link "articles" %>"
              href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              <%= "(Admin)" if current_user.admin? %> [<%= current_user.username %>] profile
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li>
                <%= link_to "View your profile", user_path(current_user), class: "dropdown-item" %>
              </li>
              <li>
                <%= link_to "Edit your profile", edit_user_path(current_user), class: "dropdown-item" %>
              </li>
              <li>
                <%= link_to "Delete your account", user_path(current_user), class: "dropdown-item text-danger",
                                                                            'data-turbo-method': :delete, data: { turbo_confirm: "Are you sure?" } %>
              </li>
            </ul>
          </li>
          <li class="nav-item">
            <%= link_to "Logout", logout_path, class: "nav-link", 'data-turbo-method': :delete %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", login_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign up", signup_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
      <form class="d-flex">
        <%= form_tag(articles_path, method: :get) do %>
        <%= text_field_tag(:search, params[:search], class: "form-control me-2", placeholder: "Search") %>
        <%= submit_tag ("Search"), class: "btn btn-outline-success" %>
        <% end %>
      </form>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Alpha Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>
  <body>
    <%= render 'layouts/navigation' %>
    <%= render 'layouts/messages' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>